### ISSUE TITLE
`WHERE` clause fails assertion at the first time `mysqld`

### ISSUE THREAD

**Issue by nikezono** [Tatzhiro/LineairDB-storage-engine#16]
Assertion failure happens when I run `bats tests/test.bats`

TODO: 
* initialize MySQL data files and restart mysqld daemon at `setup()` in `tests/test.bats`
* mysql may use caching for all queries. thus all testcases need to execute twice or more

**Comment by Tatzhiro** [comment]
MySQL seems to fail at "DROP DATABASE IF EXISTS ha_lineairdb_test;" sometimes.
Except for that error, bats test passed on my computer today.
