### ISSUE TITLE
Enable recovery

### ISSUE THREAD

**Issue by Tatzhiro** [Tatzhiro/LineairDB-storage-engine#54]
Reading and writing buf flags is not resoverable in `set_fields_from_lineairdb`, meaning that when MySQL shuts down, the information of buf flags gets lost.
Buf flags must be recoverable to get correct results from SELECT statements.
Related: #32

**Comment by Tatzhiro** [comment]
@nikezono 
Key is formatted as "table-[TABLENAME]-key-[KEY_STRING]".
Is "table-[TABLENAME]-key-" necessary?

**Comment by nikezono** [comment]
Yes. It is necessary for distinguish tables.
For example, two keys `table-user-key-alice` and `table-item-key-alice` are distinguished by table name.
Ideally, different tables should be constructed in different indices, thus this workaround is just the dirty hack.

LineairDB does not have an interface to create table such as `LineairDB::CreateTable(name)`.
This feature is in the roadmap but does not have implemented yet.
